import {TAU,clamp,sinc,raisedCosine,quantize,aliasFrequency,gaussian,qFunction,constellation,hammingEncode,hammingDecode,lineLevel,carrierValue} from './motion-models.mjs';

// A single clock drives canvases, device stages, and derivation highlights.
// No decorative cursor is used as a substitute for changing the model state.
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const C={cyan:'#45e6ce',gold:'#ffd170',pink:'#ff769b',blue:'#6d9aff',ink:'#071927',muted:'#9db5c7',white:'#eaf6ff'};
const configs={
  signal:{title:'BITS BECOME SYMBOLS',p:['Bits per symbol',1,4,1,2],n:null,note:'Bits are grouped, mapped to one of M = 2ᵏ symbols, and sent one group at a time. This is a normalized symbol timeline.'},
  sampling:{title:'WATCH EVERY SAMPLE BEING TAKEN',p:['Sampling ratio fₛ / f',1,8,.25,4],n:null,note:'The cyan tone has f = 1 cycle/unit. Gold stems appear at each sampling instant. Below fₛ/f = 2, the pink aliased tone has exactly the same sample values.'},
  quantization:{title:'AMPLITUDE → LEVEL → BINARY WORD',p:['Quantizer resolution (bits)',1,5,1,3],n:null,note:'A mid-rise uniform quantizer covers −1 to +1. Follow the moving input, rounded level and actual binary code. Quantization is not channel noise.'},
  linecode:{title:'THE SAME BITS, THREE ELECTRICAL LANGUAGES',p:['Code: 1 NRZ · 2 Manchester · 3 AMI',1,3,1,2],n:null,note:'One highlighted bit controls the live encoder. Manchester uses 1 = high-to-low and 0 = low-to-high. AMI alternates the polarity of successive ones.'},
  eye:{title:'THE EYE IS BUILT ONE SWEEP AT A TIME',p:['Raised-cosine roll-off α',0,1,.05,.35],n:['Noise standard deviation',0,.4,.01,.07],note:'Each trace is a different two-symbol window of a raised-cosine-shaped binary stream. The moving dot acquires the newest trace. Sample at the middle symbol instant.'},
  ask:{title:'ON–OFF KEYING · FOLLOW ONE BIT',p:['Carrier cycles / bit',1,6,1,3],n:['Noise standard deviation',0,.5,.01,.12],note:'Bit 1 opens the carrier gate and bit 0 closes it. The phasor, active bit and waveform cursor share the same normalized time. Pink is a sampled Gaussian-noise realization.'},
  fsk:{title:'TWO FREQUENCIES · ONE MOVING PHASE',p:['Base-tone cycles / bit',1,5,1,2],n:['Noise standard deviation',0,.5,.01,.12],note:'The two tones differ by 2 cycles/bit in this demonstration. Both have constant amplitude. Integer tone cycles keep phase continuous at bit boundaries.'},
  psk:{title:'WATCH THE 180° PHASE REVERSAL',p:['Carrier cycles / bit',1,6,1,3],n:['Noise standard deviation',0,.5,.01,.1],note:'Bit 0 uses phase 0 and bit 1 uses phase π. The rotating phasor reverses when the bit changes. Time and amplitude are normalized.'},
  constellation:{title:'TRANSMIT → DISTURB → DETECT',p:['M-PSK order: 1=4 · 2=8 · 3=16',1,3,1,1],n:['Noise σ per I/Q axis',0,.5,.01,.13],note:'Every gold point is a valid symbol with unit energy. A cyan arrow selects the transmitted symbol. The pink received observation is decoded to its nearest neighbour. Dotted paths show display transitions, not pulse-shaped RF trajectories.'},
  qam:{title:'A LIVE QAM SYMBOL DECISION',p:['QAM order: 1=4 · 2=16 · 3=64',1,3,1,2],n:['Noise σ per I/Q axis',0,.5,.01,.12],note:'The constellation has unit average symbol energy. Gaussian I/Q noise moves a transmitted symbol to a received observation. The nearest-point decision can become incorrect as noise increases.'},
  receiver:{title:'ACCUMULATE EVIDENCE · SAMPLE · DECIDE',p:['BPSK amplitude A',.5,2,.1,1],n:['Sample-noise σ',0,1,.05,.25],note:'A normalized rectangular-pulse BPSK correlator accumulates 64 noisy samples. It decides only at the end of the symbol. The displayed accumulator is a partial statistic, not a BER estimate.'},
  ber:{title:'TRACE THE ERROR-PROBABILITY CURVES',p:['Operating Eᵦ/N₀ (dB)',0,12,.5,6],n:null,note:'Analytical AWGN curves: coherent BPSK Q(√(2γ)), coherent orthogonal BFSK Q(√γ), and differential BPSK ½e⁻ᵞ. The vertical axis is logarithmic and decreases downward. The animated sweep is a parameter scan, not a measured experiment.'},
  coding:{title:'HAMMING (7,4) · ERROR AND REPAIR',p:['Flipped-bit position (1–7)',1,7,1,4],n:['Inject one error: 0=off · 1=on',0,1,1,1],note:'Four data bits become seven code bits. Exactly one controlled error is injected when enabled. The syndrome identifies its position and the decoder corrects it. This demonstration does not claim double-error correction.'},
  ofdm:{title:'ORTHOGONAL TONES, ANIMATED TOGETHER',p:['Number of subcarriers',2,8,1,5],n:['Carrier offset / subcarrier spacing',0,.5,.025,0],note:'Tone spacing is 1/Tᵤ. At zero offset, each subcarrier spectrum is zero at the other integer-frequency bins. A common carrier offset breaks that alignment. The lower plot is the normalized real part of an equal-phase OFDM symbol.'},
  sync:{title:'PHASE RECOVERY IN MOTION',p:['Initial phase offset (degrees)',0,160,5,100],n:['Residual phase jitter (degrees)',0,20,1,3],note:'The uncorrected phase offset is fixed. A first-order phase-correction demonstration drives the residual toward zero as φₑ(t) = φ₀e⁻ᵗ/², with optional sinusoidal jitter. This illustrates phase acquisition, not a complete PLL or equalizer implementation.'},
  system:{title:'A LINK WORKS AS A LIVING SYSTEM',p:['Channel gain',.2,1,.05,.7],n:['Sample-noise σ',0,.6,.02,.1],note:'A BPSK bit is mapped, attenuated by a positive channel gain, disturbed by Gaussian sample noise and sliced at zero. The same bit travels through the scene. Geometry and propagation time are illustrative.'}
};
const kind=document.body.dataset.visual||'system', cfg=configs[kind]||configs.system;
const canvases=$$('#hero-canvas,#lab-canvas,#hub-canvas');
let running=!matchMedia('(prefers-reduced-motion: reduce)').matches, time=0, speed=1, seed=7, raf=0, last=0, dirty=true;
const visible=new Set(canvases), views=new Map(canvases.map(el=>{el.width=960;el.height=600;return[el,el.getContext('2d')];}));
const p=$('#primary'), n=$('#noise'), bitsInput=$('#lab-bits');
function configure(input,def){if(!input)return;const label=input.closest('label');if(!def){label.hidden=true;return;}label.firstChild.textContent=def[0]+' ';[input.min,input.max,input.step,input.value]=def.slice(1);}
configure(p,cfg.p);configure(n,cfg.n);
const oldSpeed=$('#speed');if(oldSpeed)oldSpeed.closest('label').hidden=true;
if(bitsInput&&['sampling','quantization','eye','constellation','qam','ber','ofdm','sync'].includes(kind))bitsInput.closest('label').hidden=true;
const note=$('#observation-text');if(note)note.textContent=cfg.note;
function values(){return {p:p?+p.value:cfg.p[4],n:cfg.n?(n?+n.value:cfg.n[4]):0,bits:(bitsInput?.value||'10110100').replace(/[^01]/g,'').slice(0,12)||'10110100'};}
function updateOutputs(){const v=values();if($('#primary-out'))$('#primary-out').textContent=v.p;if($('#noise-out'))$('#noise-out').textContent=v.n;}
updateOutputs();
function paint(ctx){ctx.clearRect(0,0,960,600);const g=ctx.createLinearGradient(0,0,960,600);g.addColorStop(0,'#102c43');g.addColorStop(.5,'#071c2b');g.addColorStop(1,'#091726');ctx.fillStyle=g;ctx.fillRect(0,0,960,600);ctx.strokeStyle='#214050';ctx.lineWidth=.6;for(let x=30;x<960;x+=30){ctx.beginPath();ctx.moveTo(x,70);ctx.lineTo(x,558);ctx.stroke();}for(let y=78;y<560;y+=30){ctx.beginPath();ctx.moveTo(28,y);ctx.lineTo(932,y);ctx.stroke();}}
function text(ctx,str,x,y,color=C.muted,size=17,align='left'){ctx.save();ctx.textAlign=align;ctx.fillStyle=color;ctx.font=`${size>20?600:500} ${size}px system-ui, sans-serif`;ctx.fillText(str,x,y);ctx.restore();}
function path(ctx,points,color=C.cyan,width=2,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.restore();}
function dot(ctx,x,y,color=C.cyan,r=5){ctx.save();ctx.shadowColor=color;ctx.shadowBlur=16;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.restore();}
function circle(ctx,x,y,r,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.stroke();ctx.restore();}
function box(ctx,x,y,w,h,color='#102c40',radius=14){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,radius);ctx.fill();}
function arrow(ctx,x,y,xx,yy,color=C.cyan){path(ctx,[[x,y],[xx,yy]],color,3);const a=Math.atan2(yy-y,xx-x);path(ctx,[[xx-10*Math.cos(a-.45),yy-10*Math.sin(a-.45)],[xx,yy],[xx-10*Math.cos(a+.45),yy-10*Math.sin(a+.45)]],color,3);}
function badge(ctx,str,x,y,color=C.cyan){box(ctx,x,y-22,Math.max(70,str.length*10+24),32,'#142f42',10);text(ctx,str,x+12,y,color,16);}
function curve(ctx,fn,x,y,w,h,start=0,end=1,color=C.cyan,alpha=1){const pts=[];for(let u=start;u<=end+.0001;u+=1/420)pts.push([x+u*w,y-h*fn(u)]);if(pts.length>1)path(ctx,pts,color,2.5,alpha);}
function axis(ctx,x,y,w,h){path(ctx,[[x,y-h],[x,y+h]],'#426070',1);path(ctx,[[x,y],[x+w,y]],'#426070',1);}
function header(ctx,title,sub){text(ctx,title,34,40,C.white,21);text(ctx,sub,34,65,C.muted,14);}
function footer(ctx,str){box(ctx,24,554,912,33,'#132e40',9);text(ctx,str,40,576,C.muted,15);}
function strip(ctx,bits,u,y=115){const width=Math.min(770,bits.length*78),x=44,cw=width/bits.length;bits.split('').forEach((bit,i)=>{box(ctx,x+i*cw,y,cw-7,48,i===Math.floor(u)?'#257d79':'#142e40',10);text(ctx,bit,x+i*cw+(cw-7)/2,y+32,i===Math.floor(u)?'#fff':C.gold,24,'center');});return {x,cw,width};}
function waveScene(ctx,v,type){const total=v.bits.length,u=(time*.72)%total,k=Math.floor(u),local=u-k;header(ctx,configs[type].title,'A single normalized clock drives the bit, carrier and receiver trace');strip(ctx,v.bits,u);const fn=z=>carrierValue(type,v.bits,z*total,v.p),end=u/total;axis(ctx,45,339,650,125);curve(ctx,fn,45,339,650,95,0,1,C.cyan,.17);curve(ctx,fn,45,339,650,95,0,end,C.cyan);curve(ctx,z=>fn(z)+v.n*gaussian(Math.floor(z*512),seed),45,339,650,95,Math.max(0,end-.23),end,C.pink,.65);dot(ctx,45+650*end,339-95*fn(end));path(ctx,[[45+650*end,185],[45+650*end,472]],C.gold,1,.55);text(ctx,'t / Tᵦ →',603,494,C.muted,16);text(ctx,'normalized amplitude',45,220,C.muted,15);const b=+v.bits[k],f=type==='fsk'?v.p+2*b:v.p,angle=TAU*f*u+(type==='psk'?Math.PI*b:0),amp=type==='ask'?b:1;circle(ctx,819,318,76,'#345c70');path(ctx,[[733,318],[905,318]],'#345c70',1);path(ctx,[[819,232],[819,404]],'#345c70',1);arrow(ctx,819,318,819+70*amp*Math.cos(angle),318-70*amp*Math.sin(angle));dot(ctx,819+70*amp*Math.cos(angle),318-70*amp*Math.sin(angle));text(ctx,'CARRIER PHASOR',819,443,C.gold,15,'center');text(ctx,type==='ask'?(b?'Gate OPEN':'Gate CLOSED'):type==='fsk'?`f = ${f} cycles/bit`:`Phase = ${b?'π':'0'}`,819,469,C.white,17,'center');footer(ctx,`Bit ${k+1}/${total} = ${b}  ·  interval ${(local*100).toFixed(0)}% complete  ·  trace: cyan ideal / pink noisy`);}
function sampleScene(ctx,v){const fs=v.p,total=4,u=(time*.55)%total,fa=aliasFrequency(1,fs);header(ctx,cfg.title,`Input f = 1 cycle/unit  ·  fₛ = ${fs} samples/unit  ·  fₛ/f = ${fs}`);const fn=z=>Math.cos(TAU*z*total);axis(ctx,45,282,845,120);curve(ctx,fn,45,282,845,96,0,1,C.cyan,.6);if(fs<2)curve(ctx,z=>Math.cos(TAU*fa*z*total),45,282,845,96,0,1,C.pink,.7);const count=Math.floor(total*fs);for(let i=0;i<=count;i++){const st=i/fs,x=45+845*st/total,y=282-96*Math.cos(TAU*st),taken=st<=u;path(ctx,[[x,282],[x,y]],C.gold,taken?2:1,taken?1:.14);if(taken)dot(ctx,x,y,C.gold,4);}dot(ctx,45+845*u/total,282-96*Math.cos(TAU*u),C.cyan,8);path(ctx,[[45+845*u/total,146],[45+845*u/total,416]],C.cyan,1,.4);const i=Math.floor(u*fs),value=Math.cos(TAU*i/fs);box(ctx,45,444,845,83);text(ctx,`Sample n = ${i}`,67,477,C.gold,23);text(ctx,`x[n] = ${value.toFixed(3)}`,304,477,C.white,23);text(ctx,fs<2?`ALIASED f = ${fa.toFixed(2)}`:'No overlap: fₛ > 2f required',600,477,fs<=2?C.pink:C.cyan,19);text(ctx,'Every stem freezes the amplitude at one sampling instant.',67,509,C.muted,16);footer(ctx,'Cyan: original sinusoid  ·  gold: discrete samples  ·  pink: aliased sinusoid when undersampled');}
function quantScene(ctx,v){const u=(time*.6)%4,x=.91*Math.sin(TAU*u/4),q=quantize(x,v.p);header(ctx,cfg.title,`${q.levels} levels  ·  Δ = ${q.delta.toFixed(4)}  ·  amplitude range [−1,+1]`);curve(ctx,z=>.91*Math.sin(TAU*(z+u/4)),44,291,345,116,0,1,C.cyan,.9);text(ctx,'CONTINUOUS INPUT',45,145,C.muted,16);dot(ctx,44,291-116*x,C.cyan,9);arrow(ctx,407,291,467,291);const lx=505;for(let i=0;i<q.levels;i++){const yy=425-(i+.5)*270/q.levels;path(ctx,[[lx,yy],[lx+112,yy]],i===q.index?C.gold:'#345266',i===q.index?5:1);}const yq=290-135*q.value,yi=290-135*x;dot(ctx,lx-12,yi,C.cyan,8);path(ctx,[[lx-12,yi],[lx+112,yq]],C.gold,2);text(ctx,'QUANTIZER',503,145,C.muted,16);arrow(ctx,640,yq,683,290);box(ctx,695,221,226,147,'#123849',21);text(ctx,'BINARY OUTPUT',716,251,C.muted,16);text(ctx,q.word,808,303,C.gold,39,'center');text(ctx,`level ${q.index}`,808,341,C.white,18,'center');text(ctx,`Input ${x.toFixed(3)}`,49,480,C.cyan,21);text(ctx,`Rounded ${q.value.toFixed(3)}`,365,480,C.gold,21);text(ctx,`Error ${(q.value-x).toFixed(3)}`,709,480,C.pink,21);footer(ctx,'The moving input selects a ladder level. The output word changes only when a threshold is crossed.');}
function lineScene(ctx,v){const u=(time*.7)%v.bits.length,mode=v.p;header(ctx,cfg.title,['','Polar NRZ: 0→−1, 1→+1','Manchester: mid-bit transition','AMI: alternate only the marks'][mode]);strip(ctx,v.bits,u);const N=v.bits.length,fn=z=>lineLevel(v.bits,Math.min(N-.00001,z*N),mode);axis(ctx,45,350,854,103);curve(ctx,fn,45,350,854,79,0,1,C.cyan,.22);curve(ctx,fn,45,350,854,79,0,u/N,C.cyan);dot(ctx,45+854*u/N,350-79*fn(u/N),C.gold,8);for(let i=0;i<=N;i++)path(ctx,[[45+854*i/N,238],[45+854*i/N,457]],'#345567',1,.5);badge(ctx,`Bit ${Math.floor(u)+1}: ${v.bits[Math.floor(u)]}`,49,504,C.gold);badge(ctx,`Live level: ${fn(u/N)>0?'+':''}${fn(u/N)}`,304,504);footer(ctx,'The bright trace is the emitted part of the waveform. The faint trace previews the remaining bits.');}
function eyeScene(ctx,v){header(ctx,cfg.title,`Raised cosine α = ${v.p.toFixed(2)}  ·  one acquisition sweep takes 2 normalized symbol intervals`);const sweep=Math.floor(time*.55),u=(time*.55)%1;axis(ctx,90,318,780,153);function eye(z,trial){let s=0;const t=2*z-1;for(let k=-5;k<=5;k++)s+=(gaussian(trial*19+k,seed)>0?1:-1)*raisedCosine(t-k,v.p);return s+v.n*gaussian(Math.floor(z*160)+trial*193,seed);}for(let k=1;k<=12;k++)curve(ctx,z=>eye(z,sweep-k),90,318,780,89,0,1,k%2?C.blue:C.cyan,.15);curve(ctx,z=>eye(z,sweep),90,318,780,89,0,u,C.gold);dot(ctx,90+780*u,318-89*eye(u,sweep),C.gold,7);path(ctx,[[480,145],[480,476]],C.pink,1,.7);text(ctx,'−T',85,508);text(ctx,'0 · decision time',480,508,C.pink,18,'center');text(ctx,'+T',868,508);footer(ctx,`Acquisition ${sweep+1}: 13 overlaid two-symbol windows  ·  vertical opening = amplitude margin`);}
function constellationScene(ctx,v,type){const M=(type==='qam'?[4,16,64]:[4,8,16])[v.p-1],pts=constellation(type,M),tick=time*.55,step=Math.floor(tick),u=tick-step,idx=(step*7+seed)%M,pt=pts[idx],rx=[pt[0]+v.n*gaussian(step*2,seed),pt[1]+v.n*gaussian(step*2+1,seed)];let detected=0,best=Infinity;pts.forEach((p,i)=>{const d=(p[0]-rx[0])**2+(p[1]-rx[1])**2;if(d<best){best=d;detected=i;}});header(ctx,configs[type].title,`${M}-${type==='qam'?'QAM':'PSK'}  ·  normalized average symbol energy = 1  ·  σ = ${v.n.toFixed(2)}`);const cx=315,cy=315,scale=140;path(ctx,[[65,cy],[562,cy]],'#507181');path(ctx,[[cx,97],[cx,531]],'#507181');text(ctx,'I',546,cy-12);text(ctx,'Q',cx+12,119);pts.forEach(([x,y])=>dot(ctx,cx+scale*x,cy-scale*y,C.gold,M>16?4:6));for(let i=Math.max(0,step-18);i<step;i++){const pp=pts[(i*7+seed)%M];dot(ctx,cx+scale*(pp[0]+v.n*gaussian(i*2,seed)),cy-scale*(pp[1]+v.n*gaussian(i*2+1,seed)), '#75536d',3);}const arrive=clamp(u*3,0,1),ease=1-(1-arrive)**3;arrow(ctx,cx,cy,cx+pt[0]*scale*ease,cy-pt[1]*scale*ease);circle(ctx,cx+pt[0]*scale,cy-pt[1]*scale,14+8*Math.sin(u*Math.PI),C.cyan,.75);if(u>.34){const mix=clamp((u-.34)*3,0,1),xx=pt[0]+(rx[0]-pt[0])*mix,yy=pt[1]+(rx[1]-pt[1])*mix;path(ctx,[[cx+pt[0]*scale,cy-pt[1]*scale],[cx+xx*scale,cy-yy*scale]],C.pink,2);dot(ctx,cx+xx*scale,cy-yy*scale,C.pink,8);}box(ctx,598,142,322,340,'#102c40',22);text(ctx,`SYMBOL ${step+1}`,624,180,C.muted,17);text(ctx,u<.34?'01 · Transmit':u<.72?'02 · Add noise':'03 · Decide',624,227,C.cyan,22);text(ctx,`Sent index: ${idx}`,624,274,C.gold,22);text(ctx,`I = ${rx[0].toFixed(2)}, Q = ${rx[1].toFixed(2)}`,624,319,C.pink,19);text(ctx,u>.72?`Decision: ${detected}`:'Collecting observation…',624,365,C.white,21);if(u>.72)text(ctx,detected===idx?'Correct symbol':'Symbol error',624,412,detected===idx?C.cyan:C.pink,22);footer(ctx,'Fixed gold points: valid symbols  ·  cyan: transmitted  ·  pink: received  ·  time slowed for learning');}
function receiverScene(ctx,v){const tick=time*.4,step=Math.floor(tick),u=tick-step,bit=+v.bits[step%v.bits.length],sign=bit?-1:1;header(ctx,cfg.title,`Rectangular-pulse BPSK  ·  bit 0 → +A, bit 1 → −A  ·  amplitude ${v.p.toFixed(1)}`);const N=64,samples=Array.from({length:N},(_,i)=>sign*v.p+v.n*gaussian(step*N+i,seed)),cum=[];samples.reduce((sum,x,i)=>{cum[i]=sum+x/N;return cum[i];},0);text(ctx,'RECEIVED SAMPLES',44,118,C.muted,16);axis(ctx,45,225,532,75);curve(ctx,z=>samples[Math.min(N-1,Math.floor(z*N))]/2,45,225,532,72,0,u,C.pink);text(ctx,'CORRELATOR: PARTIAL SUM',44,346,C.muted,16);axis(ctx,45,423,532,75);curve(ctx,z=>cum[Math.min(N-1,Math.floor(z*N))]/2,45,423,532,72,0,u,C.cyan);const j=Math.min(N-1,Math.floor(u*N));dot(ctx,45+532*u,423-36*cum[j],C.cyan);box(ctx,628,135,282,350,'#102f42',23);text(ctx,'EVIDENCE',651,175,C.muted,16);text(ctx,cum[j].toFixed(3),651,221,C.cyan,33);text(ctx,`${j+1} / 64 samples`,651,262,C.white,19);text(ctx,'Zero threshold',651,306,C.muted,17);const previous=step-1,pbit=+v.bits[(previous+v.bits.length)%v.bits.length],psign=pbit?-1:1;let sum=0;for(let i=0;i<N;i++)sum+=(psign*v.p+v.n*gaussian(previous*N+i,seed))/N;const decision=sum<0?1:0;text(ctx,step?`Previous decision: ${decision}`:'First symbol collecting',651,364,C.gold,19);text(ctx,step?(decision===pbit?'Previous bit correct':'Previous bit in error'):'Wait for full interval',651,406,C.muted,17);footer(ctx,`Current transmitted bit: ${bit}  ·  receiver integrates before deciding  ·  noise samples are illustrative`);}
function berScene(ctx,v){header(ctx,cfg.title,'Analytical AWGN predictions, normalized by average energy per bit');const curves=[{name:'BPSK',c:C.cyan,fn:g=>qFunction(Math.sqrt(2*g))},{name:'BFSK',c:C.gold,fn:g=>qFunction(Math.sqrt(g))},{name:'DBPSK',c:C.pink,fn:g=>.5*Math.exp(-g)}];const x=db=>77+db/12*782,y=pb=>142+(-Math.log10(Math.max(1e-7,pb))-1)/6*357;for(let k=1;k<=7;k++){path(ctx,[[77,y(10**-k)],[858,y(10**-k)]],'#36576b',1);text(ctx,`10⁻${k}`,29,y(10**-k)+5,C.muted,15);}for(let db=0;db<=12;db+=2)text(ctx,String(db),x(db),528,C.muted,15,'center');curves.forEach((c,i)=>{const points=[];for(let db=0;db<=12;db+=.04){const pb=c.fn(10**(db/10));points.push([x(db),clamp(y(pb),111,499)]);}path(ctx,points,c.c,2.4,.78);text(ctx,c.name,96+i*260,102,c.c,18);const scan=(time*.8)%12,g=10**(scan/10);dot(ctx,x(scan),clamp(y(c.fn(g)),111,499),c.c,6);});const xx=x(v.p);path(ctx,[[xx,122],[xx,499]],C.white,1,.8);box(ctx,640,169,261,101,'#112e40',13);text(ctx,`Eᵦ/N₀ = ${v.p.toFixed(1)} dB`,654,200,C.white,20);text(ctx,`BPSK: ${curves[0].fn(10**(v.p/10)).toExponential(2)}`,654,237,C.cyan,19);footer(ctx,'Eᵦ/N₀ (dB) →  ·  lower curve means fewer errors  ·  values below 10⁻⁷ are clipped to the chart floor');}
function codingScene(ctx,v){const tick=time*.33,stage=Math.floor(tick)%4,progress=tick%1,data=v.bits.padEnd(4,'0').slice(0,4).split('').map(Number),code=hammingEncode(data),received=[...code];if(v.n)received[v.p-1]^=1;const decoded=hammingDecode(received);header(ctx,cfg.title,'Real parity bits, a controlled channel error and a computed syndrome');const labels=['Encode data + parity','Transmit through channel','Read the syndrome','Correct and recover'];badge(ctx,`${stage+1}/4 · ${labels[stage]}`,44,113);const y=243,x=69,cw=116;code.forEach((bit,i)=>{const displayed=stage>=1?received[i]:bit,isError=!!v.n&&i===v.p-1,highlight=stage===0?i<=Math.floor(progress*7):stage===2?i===decoded.syndrome-1:stage===3?isError:false;box(ctx,x+i*cw,y,98,108,highlight?(stage===3?'#175349':isError?'#62283e':'#254c63'):'#142d40',17);text(ctx,[0,1,3].includes(i)?'parity':'data',x+i*cw+49,y-18,C.muted,15,'center');text(ctx,String(stage===3?decoded.corrected[i]:displayed),x+i*cw+49,y+65,highlight?C.white:C.gold,39,'center');text(ctx,String(i+1),x+i*cw+49,y+136,C.muted,15,'center');if(highlight)circle(ctx,x+i*cw+49,y+53,36+5*Math.sin(progress*TAU),C.cyan,.6);});text(ctx,`Input: ${data.join('')}`,68,450,C.gold,24);text(ctx,stage>=2?`Syndrome: ${decoded.syndrome}`:'Syndrome: waiting',360,450,C.pink,24);text(ctx,stage===3?`Output: ${decoded.data.join('')}`:'Output: waiting',660,450,C.cyan,24);footer(ctx,v.n?`Injected error at bit ${v.p}; syndrome points to ${decoded.syndrome}; one-bit correction guaranteed for this code.`:'No channel error injected; syndrome is zero and all code bits pass unchanged.');}
function ofdmScene(ctx,v){const N=v.p,focus=Math.floor(time*.75)%N,u=(time*.3)%1;header(ctx,cfg.title,`${N} active tones  ·  Δf = 1/Tᵤ  ·  common offset = ${v.n.toFixed(3)} Δf`);const x0=62,width=817,spacing=width/(N+2);for(let k=0;k<N;k++){const center=x0+(k+1+v.n)*spacing,fn=z=>sinc((x0+z*width-center)/spacing)**2;curve(ctx,fn,x0,280,width,135,0,1,k===focus?C.gold:C.cyan,k===focus?1:.24);dot(ctx,center,145,k===focus?C.gold:C.cyan,k===focus?6:3);path(ctx,[[x0+(k+1)*spacing,124],[x0+(k+1)*spacing,294]],'#42697b',1,.5);}text(ctx,'FREQUENCY · |sinc|² spectra',63,108,C.muted,15);const sum=z=>Array.from({length:N},(_,k)=>Math.cos(TAU*(k+1+v.n)*z)).reduce((a,b)=>a+b,0)/N;axis(ctx,x0,443,width,75);curve(ctx,sum,x0,443,width,65,0,1,C.cyan,.24);curve(ctx,sum,x0,443,width,65,0,u,C.cyan);curve(ctx,z=>Math.cos(TAU*(focus+1+v.n)*z)/N,x0,443,width,65,0,u,C.gold,.9);dot(ctx,x0+u*width,443-65*sum(u),C.cyan,7);text(ctx,'TIME · real part of the summed OFDM waveform',63,346,C.muted,15);footer(ctx,`Highlighted subcarrier ${focus+1}  ·  frequency bins remain fixed  ·  ${v.n===0?'nulls align: orthogonal':'offset displaces nulls: loss of orthogonality'}`);}
function syncScene(ctx,v){const cycle=time%12,base=time*.85,error=v.p*Math.PI/180,jitter=v.n*Math.PI/180*Math.sin(time*5),residual=error*Math.exp(-cycle/2)+jitter;header(ctx,cfg.title,`Acquisition repeats every 12 display seconds  ·  initial phase offset ${v.p}°`);const angles=[base,base+error,base+residual],names=['Reference','Uncorrected','After phase correction'];angles.forEach((a,i)=>{const cx=177+i*301,cy=269,r=87,col=[C.cyan,C.pink,C.gold][i];circle(ctx,cx,cy,r,'#35576d');path(ctx,[[cx-r-18,cy],[cx+r+18,cy]],'#35576d',1);path(ctx,[[cx,cy-r-18],[cx,cy+r+18]],'#35576d',1);arrow(ctx,cx,cy,cx+r*Math.cos(a),cy-r*Math.sin(a),col);dot(ctx,cx+r*Math.cos(a),cy-r*Math.sin(a),col,7);text(ctx,names[i],cx,410,col,19,'center');});box(ctx,50,455,860,62);text(ctx,`Residual phase: ${(residual*180/Math.PI).toFixed(1)}°`,74,494,C.white,25);text(ctx,`Acquisition t = ${cycle.toFixed(1)} s`,638,494,C.gold,20);footer(ctx,'Cyan: phase reference  ·  pink: fixed phase error  ·  gold: error shrinks as the loop acquires');}
function signalScene(ctx,v){const k=v.p,padded=v.bits.padEnd(Math.ceil(v.bits.length/k)*k,'0'),groups=padded.match(new RegExp(`.{${k}}`,'g')),tick=time*.5,idx=Math.floor(tick)%groups.length,u=tick%1,word=groups[idx],value=parseInt(word,2);header(ctx,cfg.title,`k = ${k} bits/symbol  ·  M = ${2**k} possible symbols  ·  Rᵦ = kRₛ`);strip(ctx,padded,idx*k+u*k,113);const ax=209,ay=326,bx=746;circle(ctx,ax,ay,75,'#3b6277');text(ctx,word,ax,ay+12,C.gold,38,'center');text(ctx,'BIT GROUP',ax,ay+117,C.muted,16,'center');circle(ctx,bx,ay,75,'#3b6277');text(ctx,`s${value}`,bx,ay+12,C.cyan,38,'center');text(ctx,'MAPPED SYMBOL',bx,ay+117,C.muted,16,'center');path(ctx,[[ax+78,ay],[bx-78,ay]],'#42697b',3);const xx=ax+90+(bx-ax-180)*(u*u*(3-2*u));dot(ctx,xx,ay,C.gold,11);text(ctx,'map the binary label',478,ay-35,C.muted,18,'center');footer(ctx,`Current group ${idx+1}/${groups.length}: ${word} → symbol ${value}  ·  trailing zeros pad an incomplete group`);}
function systemScene(ctx,v,hub=false){const tick=time*.38,step=Math.floor(tick),u=tick-step,bit=+v.bits[step%v.bits.length],a=bit?-1:1,rx=v.p*a+v.n*gaussian(step,seed),det=rx<0?1:0;header(ctx,hub?'THE COMMUNICATION LINK IS ALIVE':cfg.title,'One information bit moves from the source, through the air, to a decision');const xs=[112,343,601,841],yy=254;for(let i=0;i<3;i++){path(ctx,[[xs[i]+58,yy],[xs[i+1]-58,yy]],'#42697b',2);const t=(u*3-i);if(t>=0&&t<=1){dot(ctx,xs[i]+59+(xs[i+1]-xs[i]-118)*t,yy,C.gold,9);text(ctx,String(bit),xs[i]+59+(xs[i+1]-xs[i]-118)*t,yy-20,C.gold,19,'center');}}xs.forEach((x,i)=>{circle(ctx,x,yy,54,i===Math.floor(u*4)?C.cyan:'#44667b');if(i===1||i===2){path(ctx,[[x-16,yy+28],[x,yy-24],[x+16,yy+28]],C.cyan,3);path(ctx,[[x-10,yy+11],[x+10,yy+11]],C.cyan,2);dot(ctx,x,yy-26,C.gold,4);for(let j=0;j<3;j++){const r=12+((time*20+j*13)%43);ctx.save();ctx.strokeStyle=C.cyan;ctx.globalAlpha=(1-r/60)*.7;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,yy-26,r,-.75,.75);ctx.stroke();ctx.restore();}}else{text(ctx,i===0?String(bit):(u>.82?String(det):'…'),x,yy+13,i===0?C.gold:C.cyan,37,'center');}text(ctx,['SOURCE','TRANSMITTER','RECEIVER','DECISION'][i],x,yy+95,C.muted,15,'center');});curve(ctx,z=>v.p*a*Math.cos(TAU*3*(z+time*.08)),53,445,835,47,0,1,C.cyan,.8);text(ctx,`Sent bit: ${bit}`,51,122,C.gold,19);text(ctx,`Gain: ${v.p.toFixed(2)} · σ: ${v.n.toFixed(2)}`,320,122,C.white,19);text(ctx,u>.82?`Decision ${det} · ${det===bit?'correct':'error'}`:'Transmission in progress',633,122,det===bit?C.cyan:C.pink,19);footer(ctx,'Animated airwaves show transmission conceptually; they are not a spatial electromagnetic-field solution.');}

const renderers={signal:signalScene,sampling:sampleScene,quantization:quantScene,linecode:lineScene,eye:eyeScene,ask:(c,v)=>waveScene(c,v,'ask'),fsk:(c,v)=>waveScene(c,v,'fsk'),psk:(c,v)=>waveScene(c,v,'psk'),constellation:(c,v)=>constellationScene(c,v,'constellation'),qam:(c,v)=>constellationScene(c,v,'qam'),receiver:receiverScene,ber:berScene,coding:codingScene,ofdm:ofdmScene,sync:syncScene,system:systemScene};
let lastStage=-1,lastDerivation=-1,lastStatus=-1,iconAnimations=[];
const nodes=$$('.flow-node'),derivationSteps=$$('.derivation-steps li');
function render(force=false){for(const animation of iconAnimations)animation.currentTime=time*1000;const v=values();for(const [canvas,ctx] of views){if(!force&&!visible.has(canvas))continue;paint(ctx);if(canvas.id==='hub-canvas')systemScene(ctx,{p:.8,n:.12,bits:'10110100'},true);else renderers[kind](ctx,v);canvas.dataset.frameTime=time.toFixed(3);}
  const stage=Math.floor(time/1.6)%Math.max(1,nodes.length);if(stage!==lastStage){nodes.forEach((el,i)=>{el.classList.toggle('active',i===stage);el.classList.toggle('processed',i<stage);el.setAttribute('aria-current',i===stage?'step':'false');});const cap=$('#flow-caption');if(cap)cap.textContent=`Stage ${stage+1}/${nodes.length}: ${nodes[stage]?.querySelector('strong')?.textContent}. The animated icon illustrates this operation; the laboratory below computes the topic-specific signal.`;lastStage=stage;}
  const deriv=Math.floor(time/4)%Math.max(1,derivationSteps.length);if(deriv!==lastDerivation){derivationSteps.forEach((el,i)=>el.classList.toggle('derivation-active',i===deriv));lastDerivation=deriv;}
  const statusTick=Math.floor(time*4);if(statusTick!==lastStatus){const el=$('#visual-readout');if(el)el.textContent=`display t = ${time.toFixed(1)} s`;lastStatus=statusTick;}
}
function syncState(){document.body.classList.toggle('motion-paused',!running);document.body.classList.add('motion-ready');document.body.style.setProperty('--motion-duration','1.6s');iconAnimations=(document.getAnimations?.()||[]).filter(a=>a.effect?.target?.closest?.('.engineering-icon'));iconAnimations.forEach(a=>a.pause());$$('[data-motion="toggle"],#motion-toggle').forEach(el=>{el.textContent=running?'Pause animation':'Play animation';el.setAttribute('aria-pressed',String(!running));});$$('[data-motion="speed"]').forEach(el=>el.value=String(speed));$$('.motion-status').forEach(el=>el.textContent=running?'Playing · time slowed for learning':'Paused · inspect or advance one step');$$('.instrument-head b').forEach(el=>{el.innerHTML=`<i></i> ${running?'playing':'paused'}`;});}
function schedule(){if(!raf&&running&&!document.hidden&&canvases.length)raf=requestAnimationFrame(loop);}
function loop(timestamp){raf=0;if(!running||document.hidden)return;const delta=last?Math.min(.08,(timestamp-last)/1000):0;last=timestamp;time+=delta*speed;render(dirty);dirty=false;schedule();}
function setRunning(value){running=value;if(raf){cancelAnimationFrame(raf);raf=0;}last=0;syncState();render(true);schedule();}
$$('[data-motion="toggle"],#motion-toggle').forEach(el=>el.addEventListener('click',()=>setRunning(!running)));
$$('[data-motion="step"]').forEach(el=>el.addEventListener('click',()=>{setRunning(false);time+=.4;render(true);}));
$$('[data-motion="restart"]').forEach(el=>el.addEventListener('click',()=>{time=0;last=0;render(true);setRunning(true);}));
$$('[data-motion="speed"]').forEach(el=>el.addEventListener('change',()=>{speed=+el.value;syncState();}));
nodes.forEach((el,i)=>el.addEventListener('click',()=>{time=(Math.floor(time/(nodes.length*1.6))*nodes.length+i)*1.6;setRunning(false);render(true);}));
function closeExpanded(){const expanded=$('.motion-expanded');if(expanded)expanded.classList.remove('motion-expanded');document.body.classList.remove('figure-open');$$('[data-motion="expand"]').forEach(el=>{el.textContent='Enlarge figure';el.setAttribute('aria-expanded','false');});}
$$('[data-motion="expand"]').forEach(el=>el.addEventListener('click',()=>{const figure=el.closest('.hero-instrument,.hero-console,.lab-chapter');if(!figure)return;const wasOpen=figure.classList.contains('motion-expanded');closeExpanded();if(!wasOpen){figure.classList.add('motion-expanded');document.body.classList.add('figure-open');el.textContent='Close large view';el.setAttribute('aria-expanded','true');}dirty=true;render(true);}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeExpanded();});
[p,n,bitsInput].forEach(el=>el?.addEventListener('input',()=>{updateOutputs();dirty=true;render(true);}));
$('#randomize')?.addEventListener('click',()=>{seed+=17;if(bitsInput)bitsInput.value=Array.from({length:8},(_,i)=>gaussian(i,seed)>0?'1':'0').join('');time=0;render(true);});
const viewportObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){visible.add(entry.target);dirty=true;}else visible.delete(entry.target);});if(!running){render();dirty=false;}},{rootMargin:'80px'});canvases.forEach(canvas=>viewportObserver.observe(canvas));
document.addEventListener('visibilitychange',()=>{last=0;document.body.classList.toggle('tab-hidden',document.hidden);if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0;}else schedule();});
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches)setRunning(false);});
syncState();render(true);schedule();
